feat: advance sort feature
approvers/rusty-ponyo pull request #106
Opened 2024-11-30 18:58 UTC by loxygenK

つよいソートを実装しました。コンソールでは動いたのでたぶん動きます。`loved_user_id` がない古い名言データでも動くはずです!

#### Added
- `--sort=<love|length|randomized>` ... ソートをします。fav 数・名言の長さ
- `--dir=<a|asc|d|desc>` ... ソート順番を変更します。デフォルトの並び順はソート種類によって異なります。
- `--reversed` … ソートの方向を入れ替えます。

### Changes
- `--random` は `--sort=randomized` のエイリアスになりました。

### Breaking changes
- `-r` は `--reversed` のエイリアスになりました。`--random` は `-R` になりました。

2024-11-30 19:19 UTC, kawaemon requested changes

2024-11-30 19:19 UTC, kawaemon commented on src/bot/meigen/mod.rs
> +    ))] // --sort and --random conflicts
`--random --sort love` の場合、ランダムにピックして、それらをいいね順にソートして表示　で成立する気がする

2024-11-30 19:19 UTC, kawaemon commented on src/bot/meigen/mod.rs
> +    ))] // --dir requires --sort
`--sort id` がデフォルト値でいいと思う。現在がそうなっているので

2024-11-30 19:19 UTC, kawaemon commented on src/bot/meigen/mod.rs
> +        reverse: bool,
```suggestion
        /// 降順にします。--dir desc のエイリアスです。
        #[clap(short, long, alias = "rev")]
        #[clap(default_value_t = false)]
        reverse: bool,
```

2024-11-30 19:19 UTC, kawaemon commented on src/bot/meigen/mod.rs
> -
すまん

2024-12-01 08:01 UTC, kawaemon commented
-r と -R 逆にすれば BC にならなくて良いのでは

2024-12-02 14:24 UTC, loxygenK commented on src/bot/meigen/mod.rs
> +    ))] // --sort and --random conflicts
する　やる（ジョイマン）

2024-12-02 14:24 UTC, loxygenK commented on src/bot/meigen/mod.rs
> +    ))] // --dir requires --sort
まかせろ

2024-12-02 14:24 UTC, loxygenK commented on src/bot/meigen/mod.rs
> +        reverse: bool,
そうする

2024-12-02 14:25 UTC, loxygenK commented on src/bot/meigen/mod.rs
> -
#107 に免じてゆるされました

2024-12-02 14:25 UTC, loxygenK commented
ただしい　そうする

2024-12-02 14:26 UTC, loxygenK commented
((trait_ext 赦されたのか))

2024-12-02 15:45 UTC, kawaemon approved these changes

2024-12-02 15:50 UTC, merged