MeigenBot
approvers/rusty-ponyo pull request #43
Opened 2023-01-16 03:38 UTC by kawaemon

2023-01-16 05:50 UTC, KisaragiEffective commented on src/bot/meigen/mod.rs
> +// pub async fn status(db: impl MeigenDatabase) -> Result<String> {
unused

2023-01-16 06:41 UTC, MikuroXina requested changes

2023-01-16 06:41 UTC, MikuroXina commented on src/bot/meigen/mod.rs
> +    async fn save(&self, author: String, content: String) -> Result<Meigen>;
```suggestion
    async fn save<A, C>(&self, author: A, content: C) -> Result<Meigen>
    where
        A: Into<String> + Send,
        C: Into<String> + Send;
```
型の範囲を広めにしておきたい

2023-01-16 06:41 UTC, MikuroXina commented on src/bot/meigen/mod.rs
> +    }
```suggestion
fn list(meigens: &[Meigen]) -> String {
    let mut res = String::new();
    let mut chars = 0;

    for meigen in meigens {
        if chars > LIST_LENGTH_LIMIT {
            res.insert_str(0, "結果が長すぎたため一部の名言は省略されました\n");
            break;
        }

        let meigen = meigen.to_string();
        chars += meigen.chars().count();
        res += &meigen;
        res += "\n";
    }
```
このスコープの大きさに対して一文字変数はよろしくないので

2023-01-16 06:41 UTC, MikuroXina commented on src/db/mem.rs
> +                true
```suggestion
                options.author.map_or(true, |a| x.author.contains(a))
                    && options.content.map_or(true, |c| x.content.contains(c))
```
もう少しきれいになるかと

2023-01-16 06:41 UTC, MikuroXina commented on src/db/mem.rs
> +        }
これって条件が逆じゃないでしょうか?

2023-01-16 06:41 UTC, MikuroXina commented on src/bot/meigen/mod.rs
> +    async fn remove_loved_user(&self, id: MeigenId, loved_user_id: u64) -> Result<bool>;
戻り値型の `bool` がどちらの意味なのか不明瞭です. ドキュメントコメントを入れるか [`ControlFlow`](https://doc.rust-lang.org/stable/std/ops/enum.ControlFlow.html) を使うかしてほしいです

2023-01-16 06:41 UTC, MikuroXina commented on src/db/mem.rs
> +        Ok(false)
どの場合でも `Ok(false)` を返していますが, 正しい動作でしょうか?

2023-01-16 07:51 UTC, kawaemon commented on src/bot/meigen/mod.rs
> +    async fn remove_loved_user(&self, id: MeigenId, loved_user_id: u64) -> Result<bool>;
[862d1a3](https://github.com/approvers/rusty-ponyo/pull/43/commits/862d1a3ddf4e10cfa312bc5bbc637d42d634ef22)

2023-01-16 09:14 UTC, MikuroXina requested changes

2023-01-16 09:14 UTC, MikuroXina commented on src/bot/meigen/mod.rs
> +                "名言が長すぎます({len}文字)。{MEIGEN_LENGTH_LIMIT}文字以下にしてください。".into(),
```suggestion
                format!("名言が長すぎます({len}文字)。{MEIGEN_LENGTH_LIMIT}文字以下にしてください。"),
```
`format!` 忘れかと

2023-01-17 00:14 UTC, MikuroXina approved these changes

2023-01-17 00:15 UTC, merged